# Uncomment this line to define a global platform for your project
# platform :ios, '8.3'

target 'GoogleMaps Example' do
source 'https://github.com/CocoaPods/Specs.git'

pod 'GoogleMaps'
end

target 'GoogleMaps ExampleTests' do

end

